debug:
  enable: false
  #  调试模式，开启后将打印所有请求和响应
# WebSocket连接配置
websocket:
  # WebSocket服务器地址
  url: "ws://127.0.0.1:3000/api"

  # 认证Token
  token: "your-auth-token-here"

# RCON配置
rcon:
  # 是否使用内置RCON（通过Bukkit API执行命令）
  # true: 使用内置方式执行命令（推荐）
  # false: 连接到外部RCON服务器
  use-builtin: true

  # 外部RCON服务器配置（仅在use-builtin为false时使用）
  host: "localhost"
  port: 25575
  password: "your-rcon-password"

# 默认语言（根据languages文件夹下的文件自动加载）
fallback-language: "zh_CN"

# 玩家进服时WebSocket不可用是否允许直接进入
allowJoinWithoutWebSocket: false
