name: FGateClient
version: ${version}
main: com.crashvibe.fgateclient.FGateClient
api-version: "1.20"

softdepend:
  - PlaceholderAPI

permissions:
  remoteclient.admin:
    description: Admin permissions for RemoteClient
    default: op
